# Generated by Django 5.1 on 2024-08-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lancamentofinanceiro_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='ativo_inativo',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
