# Generated by Django 5.1 on 2024-08-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lancamentofinanceiro_ativo_inativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='credito_debito',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='C', max_length=1),
        ),
    ]
