# Generated by Django 5.1 on 2024-08-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lancamentofinanceiro_credito_debito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='ativo_inativo',
            field=models.CharField(choices=[('I', 'Inativo'), ('A', 'Ativo')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='credito_debito',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='R$'),
        ),
    ]
